name: Run Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --alluredir=allure-results -n auto

      - name: Upload Allure results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: allure-results
